### ISSUE TITLE
Wrong format in host file

### ISSUE THREAD

**Issue by jofrep** [iocium/feedback.dangerous.domains#1]
**What domain is this regarding?*

0.0.0.0 arbirtumbridge.shop,
0.0.0.0 arbitrum-event.com,
0.0.0.0 arbitrum-labs.pw,
0.0.0.0 hop-arbitrum.exchange,

**Why is this a false positive?**
Not a false positive but the "," at the end makes the entry incompatible with pihole

**Additional context**
It will allow automatically import in pihole. At the moment these entries are ignored

**Comment by matthewgall** [comment]
Thanks for this! Also a quirk of one of the upstream public feeds that I keep finding, should be caught now!

This will be fixed in versions higher than below:

```
$ curl https://dangerous.domains/version -s | jq -r .data.blocklist
1696319502
```
