### ISSUE TITLE
Not a domain

### ISSUE THREAD

**Issue by jofrep** [iocium/feedback.dangerous.domains#2]
The following entries are not valid domains 

3commas-best
arbirtium
authorize-web
axiegrids
com12786312634
iclexofmarket
malvertising
usdc-defi-org

**Comment by matthewgall** [comment]
Thanks for this! Looks like a quirk of one of the public feeds used, I've added an additional step in the cleanup to ensure each domain has at least one . character and issued a new update to the data.

This is now fixed in data versions higher than below:

```
$ curl https://dangerous.domains/version -s | jq -r .data.blocklist
1696318943
```
