### ISSUE TITLE
[False Positive] mbcmap-dev-app.corpinter.net

### ISSUE THREAD

**Issue by vicenteIbermaticaMercedes** [iocium/feedback.dangerous.domains#4]
**What domain is this regarding?*
mbcmap-dev-app.corpinter.net

**Why is this a false positive?**
Hello, I am part of the development team of the application hosted in domain mbcmap-dev-app.corpinter.net. 
I would like to ask you for information about the reason for the inclusion of this domain in the list of dangerous domains.
I am not saying that the inclusion is not correct, but that I am not able to identify the reason why it has been included 
and we would like to have information to try to solve it.

Thanks in advance.

**Additional context**
N/A

**Comment by matthewgall** [comment]
Hello,

Apologies for the delay in responding. Your domain is listed in the Firebog Malware list at https://v.firebog.net/hosts/RPiList-Malware.txt. You may seek a correction at https://github.com/RPiList/specials/issues

**Comment by vicenteIbermaticaMercedes** [comment]
Hi again.

We opened a ticket at:  https://github.com/RPiList/specials/issues/1543 and they indidated that the our domain has been removed from the malware list, so could you removed from your list?

Thanks in advance

**Comment by matthewgall** [comment]
As the removal has been actioned by Firebog, the update automatically tricked down to dangerous.domains and is no longer listed:

```
$ curl https://dangerous.domains/list.txt -s | grep mbcmap-dev-app.corpinter.net | wc -l
0
```
