### ISSUE TITLE
[False Positive] registry-settings-app-worker.everymundo.net

### ISSUE THREAD

**Issue by ballesterdev** [iocium/feedback.dangerous.domains#5]
**What domain is this regarding?*
registry-settings-app-worker.everymundo.net

**Why is this a false positive?**
Hello, I am part of the development team (_Everymundo/PROS_) of the application hosted in domain `https://registry-settings-app-worker.everymundo.net/`.

I would like to ask you for information about the reason for the inclusion of this domain in the list of dangerous domains. I am not saying that the inclusion is not correct, but that I am not able to identify the reason why it has been included and we would like to have information to try to solve it.

Thanks in advance.

Are you the new owner of the domain? The domain is owned by _EveryMundo/PROS_ and I am allowed to manage it.

**Additional context**
N/A

**Comment by matthewgall** [comment]
Hello,

Apologies for the delay in responding. Your domain is listed in the Firebog Malware list at https://v.firebog.net/hosts/RPiList-Malware.txt. You may seek a correction at https://github.com/RPiList/specials/issues
